### ISSUE TITLE
Can't reload yaml configuration

### ISSUE THREAD

**Issue by gamba69** [amitfin/patch#33]
## System Information

version | core-2024.4.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.20-haos
arch | x86_64
timezone | Europe/Kyiv
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1473
Downloaded Repositories | 25
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.03.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 457.7 GB
disk_used | 45.9 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (17.2.0), Samba share (12.3.1), Log Viewer (0.17.0), Glances (0.21.1), Home Assistant Google Drive Backup (0.112.1), MariaDB (2.6.1), Mosquitto broker (6.4.0), Zigbee2MQTT (1.36.1-1), phpMyAdmin (0.9.1), Traccar (0.25.0), Studio Code Server (5.15.0), Network UPS Tools (0.13.0), MQTT Explorer (browser-1.0.1), Let's Encrypt (5.0.15), NGINX Home Assistant SSL proxy (3.9.0), Run On Startup.d (0.11a), Speedtest (1.5.0), HDD Tools (1.1.0), OpenSpeedTest (v2.0.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 7
views | 13
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 2 февраля 2024 г. в 09:02
-- | --
current_recorder_run | 4 апреля 2024 г. в 15:08
estimated_db_size | 3974.86 MiB
database_engine | mysql
database_version | 10.6.12

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.7.17
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 0
total_devices | 0

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/amitfin/patch/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Error when reload yaml - all configuration or specific patch integration configuration

### Reproduction steps

1. Reload yaml configuration, all or specific patch integration

### Debug logs

```text
2024-04-05 10:38:31.994 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140110015905984] Secrets not supported in this YAML file
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2542, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2579, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/patch/__init__.py", line 102, in async_reload
    config = homeassistant.config.load_yaml_config_file(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config.py", line 542, in load_yaml_config_file
    conf_dict = load_yaml_dict(config_path, secrets)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 246, in load_yaml_dict
    loaded_yaml = load_yaml(fname, secrets)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 232, in load_yaml
    return parse_yaml(conf_file, secrets)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 261, in parse_yaml
    return _parse_yaml(FastSafeLoader, content, secrets)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 288, in _parse_yaml
    return yaml.load(content, Loader=lambda stream: loader(stream, secrets))  # type: ignore[arg-type]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 428, in _handle_mapping_tag
    nodes = loader.construct_pairs(node)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yaml/constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 338, in _include_yaml
    loaded_yaml = load_yaml(fname, loader.secrets)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 232, in load_yaml
    return parse_yaml(conf_file, secrets)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 261, in parse_yaml
    return _parse_yaml(FastSafeLoader, content, secrets)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 288, in _parse_yaml
    return yaml.load(content, Loader=lambda stream: loader(stream, secrets))  # type: ignore[arg-type]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 428, in _handle_mapping_tag
    nodes = loader.construct_pairs(node)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yaml/constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 496, in secret_yaml
    raise HomeAssistantError("Secrets not supported in this YAML file")
homeassistant.exceptions.HomeAssistantError: Secrets not supported in this YAML file
```

**Comment by amitfin** [comment]
What are you trying to achieve? 
Can you share the `patch:` section of your configuration (`configuration.yaml`).
It's hard to tell from the logs, but my guess is that you have an invalid `patch:` section. 
Please verify your configuration against the [documentation](https://github.com/amitfin/patch?tab=readme-ov-file#configuration). (You can also validate it against the actual validation code which can be found [here](https://github.com/amitfin/patch/blob/3772b2a8cc7b4d51356a8ed28d0a9196ee46900d/custom_components/patch/__init__.py#L72)).

**Comment by gamba69** [comment]
> What are you trying to achieve? Can you share the `patch:` section of your configuration (`configuration.yaml`). It's hard to tell from the logs, but my guess is that you have an invalid `patch:` section. Please verify your configuration against the [documentation](https://github.com/amitfin/patch?tab=readme-ov-file#configuration). (You can also validate it against the actual validation code which can be found [here](https://github.com/amitfin/patch/blob/3772b2a8cc7b4d51356a8ed28d0a9196ee46900d/custom_components/patch/__init__.py#L72)).

patch:
  delay: 60
  files:
    - name: "adb_manager_async.py"
      base: "/config/patches/base/androidtv/adb_manager"
      destination: "{site-packages}/androidtv/adb_manager"
      patch: "/config/patches/patched/androidtv/adb_manager"
    - name: "adb_manager_sync.py"
      base: "/config/patches/base/androidtv/adb_manager"
      destination: "{site-packages}/androidtv/adb_manager"
      patch: "/config/patches/patched/androidtv/adb_manager"

All work fine. Files patches apply, after HA update patch initiate reload. But I can't reload yaml confg from developer panel, neither "all" no "patch" with error specified.

**Comment by gamba69** [comment]
![изображение](https://github.com/amitfin/patch/assets/1047018/d1336eb1-93e0-4379-88d6-4bfc22e5b67d)

**Comment by amitfin** [comment]
Why do you think the problem is related to the patch integration?
In both places, the log and the screenshot, it seems that the problem is related to secrets:

_Secrets not supported in this YAML file_

**Comment by gamba69** [comment]
> Why do you think the problem is related to the patch integration? In both places, the log and the screenshot, it seems that the problem is related to secrets:
> 
> _Secrets not supported in this YAML file_

Main reason: When I comment out patch configuration - all reload's work as usual. After uncommenting - this error rise again.

**Comment by LordShadowen** [comment]
I know this is closed, but have exactly the same issue, exactly as described by @gamba69 - and I'm hoping you could take a second look at this.

If I add a 'patch' section to my config, everything related to patching works great, but I can't reload YAML  or do a quick reload - I get the same 'Secrets not supported in this YAML file' error and exact same error on the log.

If I comment out the section and restart HA, then everything goes back to normal.

I recognize it's a bit weird - doesn't seem related, and there's definitely nothing related to secrets going on... but the fact is, it happens :)

**Comment by AudunVN** [comment]
Getting the same here - think it might be due to not passing secrets in to `homeassistant.config.load_yaml_config_file` at

https://github.com/amitfin/patch/blob/2344b7423515356b5c9826a25c280417691206d0/custom_components/patch/__init__.py#L102-L106

Raising that error here when not passing `secrets` appear to be the expected behavior as per https://github.com/home-assistant/core/blob/60e3b38de1fe86523cd520db63dcc956fdc6b2c2/tests/util/yaml/test_init.py#L419-L424, not sure what a fix for this would look like (yet).
